CREATE TABLE SeatingChart (
  FLOOR_SEAT_SEQ INT PRIMARY KEY,
  FLOOR_NO INT,
  SEAT_NO INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE Employee (
  EMP_ID VARCHAR(5) PRIMARY KEY,
  NAME VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  EMAIL VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  FLOOR_SEAT_SEQ INT,
  FOREIGN KEY (FLOOR_SEAT_SEQ) REFERENCES SeatingChart(FLOOR_SEAT_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;




